name: Deploy site

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!.github/workflows/prettier.yml"
      - "!.github/workflows/render-cv.yml"
      - "!.github/workflows/update-citations.yml"
      - "!lighthouse_results/**"
      - "!docs/**"
      - "!README.md"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!.github/workflows/prettier.yml"
      - "!.github/workflows/render-cv.yml"
      - "!.github/workflows/update-citations.yml"
      - "!lighthouse_results/**"
      - "!docs/**"
      - "!README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies
      - name: Setup Node 🧰
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install JS deps 📦
        run: npm ci
      - name: Cache Jekyll metadata ♻️
        uses: actions/cache@v4
        with:
          path: |
            .jekyll-cache
            .tweet-cache
          key: jekyll-cache-${{ runner.os }}-${{ hashFiles('_bibliography/**', '_config.yml') }}
          restore-keys: |
            jekyll-cache-${{ runner.os }}-
      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          propertyPath: "giscus.repo"
          value: ${{ github.repository }}
      - name: Install and Build 🔧
        run: |
          pip3 install nbconvert
          export JEKYLL_ENV=production
          bundle exec jekyll build
      - name: Purge unused CSS 🧹
        run: npx --yes purgecss@6.0.0 -c purgecss.config.js
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
